//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace testApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productCart
    {
        [Key][JsonIgnore]
        public int idCart { get; set; }
        [Key][JsonIgnore]
        public int idProduct { get; set; }
        public int quantity { get; set; }
    
        [ForeignKey("idProduct")]
        public virtual product product { get; set; }
    }
}
